const card_data = {
    1: {
        name: "Cross Trainers",
        // effect: "+20% Stamina \n+20% Stamina Regen \n+3% Move Speed \n+5 health\n",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info: [],
    },
    2: {
        name:"Energy Drink",
        // effect:"+15% Stamina \n+25% Weapon Swap Speed \n+15% Move Speed while firing\n +10% Slow Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:[],
    },
    3: {
        name:"Rhythmic Breathing",
        // effect:"+40% Stamina",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:[],
    },
    4: {
        name:"Reload Drills",
        // effect:"+20% Reload Speed \n +25% Weapon Swap Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:[],
    },
    5: {
        name:"Widemouth Magwell",
        // effect:"+30% Reload Speed \n -5% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Resistance: Reduces incoming damage (max: 90%)."],
    },
    6: {
        name:"Mag Coupler",
        // effect:"+50% Reload Speed \n DISABLES: Aim Down Sights",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:[],
    },
    7: {
        name:"Slugger",
        // effect:"+5% Health \n+10% Melee Stamina Efficiency \n+20% Melee Attack Speed \n+10% Bow Stamina Efficiency \n+20% Bow Attack Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:[],
    },
    8: {
        name:"Brazen",
        // effect:"+15% Meleee Stamina Efficiency \n+20% Melee Attack Speed \n+15% Bow Stamina Efficiency \n+20% Bow Attack Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:[],
    },
    9: {
        name:"Meth Head",
        // effect:"Each Melee swing grants 5% Melee Speed and 5% melee Stamina Efficiency for 6 seconds, stacking up to 10 times. You Melee Attacks no longer stick in tough enemies. \nDISABLES: Aim Down Sights",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:[],
    },
    10: {
        name:"Ridden Slayer",
        // effect:"+20% Weakspot Damage",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Weakspot: Most enmies have Weakspots that take extra damage when hit."],
    },
    11: {
        name:"Reckless Strategy",
        // effect:"+30% Weakspot Damage \n-5% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.", "Resistance: Reduces incoming damage (max: 90%)."],
    },
    12: {
        name:"Hyper-Focused",
        // effect:"+50% Weakspot Damage \n-40% Move Speed shile shooting or melee attacking.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.",],
    },
    13 : {
        name:"Hi Vis Sights",
        // effect:"+30% Aim Speed \n+15% Move Speed while ADS \n+15% Move Speed while firing",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    14: {
        name:"Tunnel Vision",
        // effect:"Every 0.75 seconds you Aim Down Sights gives 5% Weakspot Damage (up to 3 stacks). \n+50% Aim Speed \n-5% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.", "Resistance: Reduces incoming damage (max: 90%)."],    
    },
    15: {
        name:"Steady Aim",
        // effect:"Every 0.75 seconds you Aim Down Sights gives 10% Recoil Control (up to 3 stacks). \n+80% Aim Speed \n-50% ADS Move Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    16: {
        name:"Shooting Gloves",
        // effect:"+25% Weapon Swap Speed \n+15% Recoil Control \n+15% Accuracy",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["",],
    },
    17: {
        name:"Cuns Out",
        // effect:"+50% Weapon Swap Speed \n -5% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard"
        // info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    18: {
        name:"Cocky",
        // effect:"+75% Weapon Swap Speed \nWhen you take damage, your Accuracy is reduced for 3 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["",],
    },
    19: {
        name:"Smelling Salts",
        // effect:"+200% Revive Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["",],
    },
    20: {
        name:"Pep Talk",
        // effect:"While Reviving Teammates, take 3 less damage from all Ridden. Teammates recover and additional 10 Health When you revive them.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["",],
    },
    21: {
        name:"Rousing Speech",
        // effect:"",
        // team_effects:"Teammates recover and additional 10 Health when revived \n+50% Team Revive Speed \n+10% Team Reduced Incap Trauma",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["Team Effect: This card applies to you and your teammates.", "Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",],
    },
    22: {
        name:"Dash",
        // effect:"+5% Move Speed \n +5% Sprint Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    23: {
        name:"Fleet Of Foot",
        // effect:"+8% Move Speed",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    24: {
        name:"Run Like Hell",
        // effect:"+12% Move Speed \n+15% Sprint Speed \nWhen you take damage, you lose the benefits of Run like Hell for 3 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    25: {
        name:"Superior Cardio",
        // effect:"+20% Stamina \n+20% Sprint Efficiency \n+5 Health",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    26: {
        name:"Olympic Sprinter",
        // effect:"+30% Sprint Efficiency \n-7% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    27: {
        name:"Reckless",
        // effect:"+40% Sprint Efficiency \nWhen you take damage while Sprinting, you lose all Stamina.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    28: {
        name:"Breakout",
        // effect:"Breakout: Hold [E] to free yourself from Grabs. \n+50% Breakout Cooldown Reduction.(Base 60 Seconds.)",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["Grab: Grabs or Grapples refer to enemy abilities that restrict movement.",],
    },
    29: {
        name:"Combat Medic",
        // effect:"+50% Use Speed \n Teammates recover an additional 20 Health when you revive them.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Defense",
        // expansion: "Standard",
        // info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    30: {
        name:"Fire In The Hole!",
        // effect:"When you throw and Offensive Accessory, gain 20 Temporary Health and 25% Sprint Speed for 5 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    31: {
        name:"Medical Expert",
        // effect:"+50% Revive Speed \nWhen you use a Medical Accessory, it also heals 1 Trauma to the target.",
        // team_effects:"+15% Healing Efficiency",
        // affinity: "Reflex",
        // card_type: "Defense",
        // expansion: "Standard",
        // info:["Team Effect: This card applies to you and your teammates.", "Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.", "Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",],
    },
    32: {
        name:"Rolling Thunder",
        // effect:"+35% Move Speed while firing with Shotguns. \n+10% Damage with Shotguns.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    33: {
        name:"Speed Demon",
        // effect:"+4% Move Speed while using an SMG. \n +35% Reload Speed while using an SMG.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    34: {
        name:"Hellfire",
        // effect:"+45% Move Speed while firing. \n+3% Move Speed while not firing.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    35: {
        name:"Marathon Runner",
        // effect:"No Movement Penalty for strafe and backpedal.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    36: {
        name:"Mandatory PT",
        // effect:"",
        // team_effects:"+10% Team Stamina \n+10% Team Stamina Regen",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["Team Effect: This card applies to you and your teammates."],
    },
    37: {
        name:"Pep In Your Step",
        // effect:"Precision Kills grant you 8% Move Speed for 5 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    38: {
        name:"Shredder",
        // effect:"Each bullet hit causes the target to take 1% increased damage for 3 seconds (stacks up to 15%).",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    39: {
        name:"Class Cannon",
        // effect:"+25% Damage \n-30% Health",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    40: {
        name:"Sadistic",
        // effect:"Each Precision Kill gives 5% increased Weakspot Damage for 10 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.","Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    41: {
        name:"Adrenaline Fueled",
        // effect:"When you kill an enemy, gain 5 Stamina instantly and an additional 7 Stamina over 7 seconds, stacking up to 5 times.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    42: {
        name:"Miraculous Recovery",
        // effect:"When you use a Medical Accessory, it has a 25% chance to have 100% increased effect.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Defense",
        // expansion: "Standard",
        // info:["",],
    },
    43: {
        name:"Screwdriver",
        // effect:"+50% Use Speed \n+10% Stamina",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    44: {
        name:"Multitool",
        // effect:"+75% Use Speed \n-5% Damage Resistance",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.", "Resistance: Reduces incoming damage (max: 90%)."],
    },
    45: {
        name:"Headband Magnifier",
        // effect:"+125% Use Speed \nWhen you take damage, you have a chance to be blinded for 1 second.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    46: {
        name:"Utility Scavenger",
        // effect:"You can sense nearby Quick Accessories. \n More Quick Accessories spawn.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Standard",
        // info:["",],
    },
    47: {
        name:"Stimulants",
        // effect:"Pain Meds you apply also grant \n+20% Stamina Regen, \n+15% Reload Speed, and \n+15% Weapon Swap Speed for 60 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    48: {
        name:"On Your Mark....",
        // effect:"",
        // team_effects:"When a horde is triggered, your team restores 7.5% Ammo and gains 10% Move Speed while firing, 15% Reload Speed, and 25% Swap Speed for 30 seconds.",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["Team Effect: This card applies to you and your teammates."],
    },
    49: {
        name:"Killer's Instinct",
        // effect:"+30% Weakspot Damage \nDISABLES: Aim Down Sights",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    50: {
        name:"Power Swap",
        // effect:"Changing weapons within 1 second of reaching low ammo grants +20% Bullet and Melee Damage for 5 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    51: {
        name:"Stock Pouch",
        // effect:"+30% Sniper Ammo Capacity \n+10% Damage with Sniper Rifles",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    52: {
        name:"Mag Carrier",
        // effect:"+30% Pistol/SMG Ammo Capacity \n+10% Damage with Pistols and SMGs",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    53: {
        name:"Mad Dash",
        // effect:"+20% Sprint Speed \n-40% Sprint Stamina Efficiency",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Mobility",
        // expansion: "Standard",
        // info:["",],
    },
    54: {
        name:"Stealthy Passage",
        // effect:"Allows disarming of door alarms, car alarms, and birds. The target will trigger if you are interrupted. \nDISABLES: Quick Slot",
        // team_effects:"Gain 25 Copper per success.",
        // affinity: "Reflex",
        // card_type: "Utility",
        // expansion: "Tunnels of Terror"
        // info:["Team Effect: This card applies to you and your teammates.","Birds: If you get too close, birds will fly off and alert the Horde. Crouching reducs the distance they get startled from."],
    },
    55: {
        name:"Pumped Up",
        // effect:"Your Temporary Health decays 20% slower. \n1 Additional Pain Meds spawns in each map. \n+5% Health",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Defense",
        // expansion: "Tunnels of Terror"
        // info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    56: {
        name:"Experimental Stimulants",
        // effect:"Create a cloud that grants 20% Damage and 30% Reload speed. \nGadget Cost: 40[Rifle Ammo] \nREPLACES: Support Slot",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Children of the Worm"
        // info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.",],
    },
    57: {
        name:"Fill'Em Full Of Lead",
        // effect:"While shooting, gain 1% Damage, 1% fire rate, and 5% swap speed every 0.25 seconds. Max count of buffs is 20.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Children of the Worm"
        // info:["",],
    },
    58: {
        name:"Supressing Fire",
        // effect:"Damaging Ridden with LMGs and Snipers has a 40% chance to slow Ridden near the target by 50% for 5 seconds.",
        // team_effects:"",
        // affinity: "Reflex",
        // card_type: "Offense",
        // expansion: "Children of the Worm"
        // info:["",],
    },
    59: {
        name:"Ammo Pouch",
        // effect:"25% Ammo Capacity \n+2.5% Bullet Damage",
        // team_effects:"",
        // affinity: "Discipline",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },
    60: {
        name:"Ammo Belt",
        // effect:"+50% Ammo Capacity \n+15% Reload Speed",
        // team_effects:"",
        // affinity: "Discipline",
        // card_type: "Offense",
        // expansion: "Standard",
        // info:["",],
    },


    // : {
    //     name:"",
    //     // effect:"",
    //     // team_effects:"",
    //     // affinity: "",
    //     // card_type: "",
    //     // expansion: "Standard",
    //     // info:["",],
    // },

};

module.exports = card_data;