const card_data = {
    1: {
        name: "Cross Trainers",
        effect: "+20% Stamina \n+20% Stamina Regen \n+3% Move Speed \n+5 health\n",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info: [],
    },
    2: {
        name:"Energy Drink",
        effect:"+15% Stamina \n+25% Weapon Swap Speed \n+15% Move Speed while firing\n +10% Slow Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:[],
    },
    3: {
        name:"Rhythmic Breathing",
        effect:"+40% Stamina",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:[],
    },
    4: {
        name:"Reload Drills",
        effect:"+20% Reload Speed \n +25% Weapon Swap Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    5: {
        name:"Widemouth Magwell",
        effect:"+30% Reload Speed \n -5% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%)."],
    },
    6: {
        name:"Mag Coupler",
        effect:"+50% Reload Speed \n DISABLES: Aim Down Sights",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    7: {
        name:"Slugger",
        effect:"+5% Health \n+10% Melee Stamina Efficiency \n+20% Melee Attack Speed \n+10% Bow Stamina Efficiency \n+20% Bow Attack Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    8: {
        name:"Brazen",
        effect:"+15% Meleee Stamina Efficiency \n+20% Melee Attack Speed \n+15% Bow Stamina Efficiency \n+20% Bow Attack Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    9: {
        name:"Meth Head",
        effect:"Each Melee swing grants 5% Melee Speed and 5% melee Stamina Efficiency for 6 seconds, stacking up to 10 times. You Melee Attacks no longer stick in tough enemies. \nDISABLES: Aim Down Sights",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    10: {
        name:"Ridden Slayer",
        effect:"+20% Weakspot Damage",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit."],
    },
    11: {
        name:"Reckless Strategy",
        effect:"+30% Weakspot Damage \n-5% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.", "Resistance: Reduces incoming damage (max: 90%)."],
    },
    12: {
        name:"Hyper-Focused",
        effect:"+50% Weakspot Damage \n-40% Move Speed shile shooting or melee attacking.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.",],
    },
    13 : {
        name:"Hi Vis Sights",
        effect:"+30% Aim Speed \n+15% Move Speed while ADS \n+15% Move Speed while firing",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    14: {
        name:"Tunnel Vision",
        effect:"Every 0.75 seconds you Aim Down Sights gives 5% Weakspot Damage (up to 3 stacks). \n+50% Aim Speed \n-5% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.", "Resistance: Reduces incoming damage (max: 90%)."],    
    },
    15: {
        name:"Steady Aim",
        effect:"Every 0.75 seconds you Aim Down Sights gives 10% Recoil Control (up to 3 stacks). \n+80% Aim Speed \n-50% ADS Move Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    16: {
        name:"Shooting Gloves",
        effect:"+25% Weapon Swap Speed \n+15% Recoil Control \n+15% Accuracy",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["",],
    },
    17: {
        name:"Cuns Out",
        effect:"+50% Weapon Swap Speed \n -5% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    18: {
        name:"Cocky",
        effect:"+75% Weapon Swap Speed \nWhen you take damage, your Accuracy is reduced for 3 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["",],
    },
    19: {
        name:"Smelling Salts",
        effect:"+200% Revive Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["",],
    },
    20: {
        name:"Pep Talk",
        effect:"While Reviving Teammates, take 3 less damage from all Ridden. Teammates recover and additional 10 Health When you revive them.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["",],
    },
    21: {
        name:"Rousing Speech",
        effect:"",
        team_effects:"Teammates recover and additional 10 Health when revived \n+50% Team Revive Speed \n+10% Team Reduced Incap Trauma",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.", "Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",],
    },
    22: {
        name:"Dash",
        effect:"+5% Move Speed \n +5% Sprint Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    23: {
        name:"Fleet Of Foot",
        effect:"+8% Move Speed",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    24: {
        name:"Run Like Hell",
        effect:"+12% Move Speed \n+15% Sprint Speed \nWhen you take damage, you lose the benefits of Run like Hell for 3 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    25: {
        name:"Superior Cardio",
        effect:"+20% Stamina \n+20% Sprint Efficiency \n+5 Health",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    26: {
        name:"Olympic Sprinter",
        effect:"+30% Sprint Efficiency \n-7% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    27: {
        name:"Reckless",
        effect:"+40% Sprint Efficiency \nWhen you take damage while Sprinting, you lose all Stamina.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    28: {
        name:"Breakout",
        effect:"Breakout: Hold [E] to free yourself from Grabs. \n+50% Breakout Cooldown Reduction.(Base 60 Seconds.)",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Grab: Grabs or Grapples refer to enemy abilities that restrict movement.",],
    },
    29: {
        name:"Combat Medic",
        effect:"+50% Use Speed \n Teammates recover an additional 20 Health when you revive them.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Defense",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    30: {
        name:"Fire In The Hole!",
        effect:"When you throw and Offensive Accessory, gain 20 Temporary Health and 25% Sprint Speed for 5 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    31: {
        name:"Medical Expert",
        effect:"+50% Revive Speed \nWhen you use a Medical Accessory, it also heals 1 Trauma to the target.",
        team_effects:"+15% Healing Efficiency",
        affinity: "Reflex",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.", "Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.", "Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",],
    },
    32: {
        name:"Rolling Thunder",
        effect:"+35% Move Speed while firing with Shotguns. \n+10% Damage with Shotguns.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    33: {
        name:"Speed Demon",
        effect:"+4% Move Speed while using an SMG. \n +35% Reload Speed while using an SMG.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    34: {
        name:"Hellfire",
        effect:"+45% Move Speed while firing. \n+3% Move Speed while not firing.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    35: {
        name:"Marathon Runner",
        effect:"No Movement Penalty for strafe and backpedal.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    36: {
        name:"Mandatory PT",
        effect:"",
        team_effects:"+10% Team Stamina \n+10% Team Stamina Regen",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates."],
    },
    37: {
        name:"Pep In Your Step",
        effect:"Precision Kills grant you 8% Move Speed for 5 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    38: {
        name:"Shredder",
        effect:"Each bullet hit causes the target to take 1% increased damage for 3 seconds (stacks up to 15%).",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    39: {
        name:"Class Cannon",
        effect:"+25% Damage \n-30% Health",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    40: {
        name:"Sadistic",
        effect:"Each Precision Kill gives 5% increased Weakspot Damage for 10 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.","Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    41: {
        name:"Adrenaline Fueled",
        effect:"When you kill an enemy, gain 5 Stamina instantly and an additional 7 Stamina over 7 seconds, stacking up to 5 times.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    42: {
        name:"Miraculous Recovery",
        effect:"When you use a Medical Accessory, it has a 25% chance to have 100% increased effect.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Defense",
        expansion: "Standard",
        info:["",],
    },
    43: {
        name:"Screwdriver",
        effect:"+50% Use Speed \n+10% Stamina",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    44: {
        name:"Multitool",
        effect:"+75% Use Speed \n-5% Damage Resistance",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.", "Resistance: Reduces incoming damage (max: 90%)."],
    },
    45: {
        name:"Headband Magnifier",
        effect:"+125% Use Speed \nWhen you take damage, you have a chance to be blinded for 1 second.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    46: {
        name:"Utility Scavenger",
        effect:"You can sense nearby Quick Accessories. \n More Quick Accessories spawn.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Standard",
        info:["",],
    },
    47: {
        name:"Stimulants",
        effect:"Pain Meds you apply also grant \n+20% Stamina Regen, \n+15% Reload Speed, and \n+15% Weapon Swap Speed for 60 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    48: {
        name:"On Your Mark....",
        effect:"",
        team_effects:"When a horde is triggered, your team restores 7.5% Ammo and gains 10% Move Speed while firing, 15% Reload Speed, and 25% Swap Speed for 30 seconds.",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates."],
    },
    49: {
        name:"Killer's Instinct",
        effect:"+30% Weakspot Damage \nDISABLES: Aim Down Sights",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    50: {
        name:"Power Swap",
        effect:"Changing weapons within 1 second of reaching low ammo grants +20% Bullet and Melee Damage for 5 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    51: {
        name:"Stock Pouch",
        effect:"+30% Sniper Ammo Capacity \n+10% Damage with Sniper Rifles",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    52: {
        name:"Mag Carrier",
        effect:"+30% Pistol/SMG Ammo Capacity \n+10% Damage with Pistols and SMGs",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    53: {
        name:"Mad Dash",
        effect:"+20% Sprint Speed \n-40% Sprint Stamina Efficiency",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Mobility",
        expansion: "Standard",
        info:["",],
    },
    54: {
        name:"Stealthy Passage",
        effect:"Allows disarming of door alarms, car alarms, and birds. The target will trigger if you are interrupted. \nDISABLES: Quick Slot",
        team_effects:"Gain 25 Copper per success.",
        affinity: "Reflex",
        card_type: "Utility",
        expansion: "Tunnels of Terror",
        info:["Team Effect: This card applies to you and your teammates.","Birds: If you get too close, birds will fly off and alert the Horde. Crouching reducs the distance they get startled from."],
    },
    55: {
        name:"Pumped Up",
        effect:"Your Temporary Health decays 20% slower. \n1 Additional Pain Meds spawns in each map. \n+5% Health",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    56: {
        name:"Experimental Stimulants",
        effect:"Create a cloud that grants 20% Damage and 30% Reload speed. \nGadget Cost: 40[Rifle Ammo] \nREPLACES: Support Slot",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.",],
    },
    57: {
        name:"Fill'Em Full Of Lead",
        effect:"While shooting, gain 1% Damage, 1% fire rate, and 5% swap speed every 0.25 seconds. Max count of buffs is 20.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Children of the Worm",
        info:["",],
    },
    58: {
        name:"Supressing Fire",
        effect:"Damaging Ridden with LMGs and Snipers has a 40% chance to slow Ridden near the target by 50% for 5 seconds.",
        team_effects:"",
        affinity: "Reflex",
        card_type: "Offense",
        expansion: "Children of the Worm",
        info:["",],
    },
    59: {
        name:"Ammo Pouch",
        effect:"25% Ammo Capacity \n+2.5% Bullet Damage",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    60: {
        name:"Ammo Belt",
        effect:"+50% Ammo Capacity \n+15% Reload Speed",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    61: {
        name:"Ammo Mule",
        effect:"+75% Ammo Capacity \n-5% Move Speed",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    62: {
        name:"Front Sight Focus",
        effect:"+20% Accuracy \n+10% Weakspot Damage \n+15% Aim Speed \n+15% Recoil Control",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.",],
    },
    63: {
        name:"Optics Enthusiast",
        effect:"+30% Accuracy",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    64: {
        name:"Quick Kill",
        effect:"+50% Accuracy \nDISABLES: Aim Down Sights",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["",],
    },
    65: {
        name:"Motorcycle Jacket",
        effect:"+5% Damage Resistance \n+5 Health",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    66: {
        name:"Padded Suit",
        effect:"+10% Damage Resistance \n+5 Health \n-20% Stamina Efficiency",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    67: {
        name:"Motorcycle Helmet",
        effect:"+15% Damage Resistance \n+10 Health \nDISABLES: Aim Down Sights",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    68: {
        name:"Combat Training",
        effect:"+5% Bullet Damage \n+1.5 Bullet Stumble Damage \n+7.5 Melee Stumble Damage",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Stumble: Stumble is a special damage type that builds up and interrupts enemies.",],
    },
    69: {
        name:"Large Caliber Rounds",
        effect:"+7.5% Bullet Damage \n+200% Bullet Penetration",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    70: {
        name:"Silver Bullets",
        effect:"10% Bullet Damage \n+15% Effective Bullet Range",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    71: {
        name:"Antibiotic Ointment",
        effect:"+25% Healing Efficiency \nWhen you use a Medical Accessory, the target heals 20 Temporary Health.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses."],
    },
    72: {
        name:"EMT Bag",
        effect:"+50% Healing Efficiency",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    73: {
        name:"Field Surgeon",
        effect:"When you use a Medical Accessory, it also heals 3 Trauma to the target.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses."],
    },
    74: {
        name:"Energy Bar",
        effect:"30% Stamina Regeneration \n+5 Health",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Mobility",
        expansion: "Standard",
        info:[,],
    },
    75: {
        name:"Cold Brew Coffee",
        effect:"+15% Reload Speed \n25% Aim Speed \n25% Weapon Swap Speed \n+25% Use Speed",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Mobility",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    76: {
        name:"Natural Sprinter",
        effect:"+100% Stamina Regeneration \n-50% Maximum Stamina",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Mobility",
        expansion: "Standard",
        info:[,],
    },
    77: {
        name:"Inspiring Sacrifice",
        effect:"",
        team_effects:"When you or a teammate becomes incapacitated, all teammates recover 20 health over 10 seconds.",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    78: {
        name:"Charitable Soul",
        effect:"Healing a teammate also applies 50% of the effect to you.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:[,],
    },
    79: {
        name:"Hunker Down",
        effect:"While crouching, gain 10% Damage Resistance and 40% Accuracy.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    80: {
        name:"Avenge The Fallen",
        effect:"",
        team_effects:"When you or a teammate becomes incapacitated, all teammates gain 30% Damage, 20% Reload Speed, and Unlimited Ammo for 10 seconds.",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    81: {
        name:"Vanguard",
        effect:"Melee kills heal 1 Health to yourself, and teammates within 10 meters.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    82: {
        name:"In The Zone",
        effect:"Precision Kills grant 5% Reload Speed for 5 seconds (stacking up to 10 times).",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    83: {
        name:"Trigger Control",
        effect:"Trigger Control",
        team_effects:"Precision Kills with guns grant +0.5% Accuracy until the end of the level.",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    84: {
        name:"Needs Of The Many",
        effect:"-10% Health",
        team_effects:"+1 Team Extra Life",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.","Extra Life: Each Extra Life increases the number of times you can be incapacitated without dying."],
    },
    85: {
        name:"Combat Knife",
        effect:"Turns your Bash into a Knife that counts as a Melee weapon.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    86: {
        name:"Meatgrinder",
        effect:"Gain 30% Move Speed and Accuracy while crouched and using an LMG.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    87: {
        name:"Scattergun Skills",
        effect:"+40% Reload Speed with Shotguns.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    88: {
        name:"Controlled Movement",
        effect:"+40% Move Speed while aiming down sights with Sniper Rifles.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Mobility",
        expansion: "Standard",
        info:[,],
    },
    89: {
        name:"Ammo For All",
        effect:"",
        team_effects:"+10% Team Ammo Capacity \n+3.5% Team Damage",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    90: {
        name:"Down In Front!",
        effect:"While crouching you neither take nor deal Friendly Fire damage. \n + 10 Health",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:[,],
    },
    91: {
        name:"Poultice",
        effect:"When you use a Medical Accessory, the target recovers an additional 20 Health over 30 seconds.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:[,],
    },
    92: {
        name:"Group Therapy",
        effect:"When you use a Medical Accessory, all teammates heal for 8 Health.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    93: {
        name:"Medical Professional",
        effect:"Defibrillators and First Aid heal 10 additional Trauma Damage and 1 Extra Life, if able.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:[
            "Extra Life: Each Extra Life increases the number of times you can be incapacitated without dying.",
            "Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",
            "Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses."
        ],
    },
    94: {
        name:"Ammo Scavenger",
        effect:"You can sense nearby Ammo. \n1 additional Ammo crate spawn.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:[,],
    },
    95: {
        name:"Support Scavenger",
        effect:"You can sense nearby Support Accessories. \n More Support Accessories spawn.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:[,],
    },
    96: {
        name:"Weapon Scavenger",
        effect:"You can sense nearby weapons. \nMore weapons spawn.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:[,],
    },
    97: {
        name:"Amped Up",
        effect:"",
        team_effects:"When a horde is triggered, your team recovers 20 Health.",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    98: {
        name:"Patient Hunter",
        effect:"Every 0.75 seconds you Aim Down Sights increases your Bullet Damage by 10% (up to 3 stacks).",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    99: {
        name:"Power Reload",
        effect:"Reloading a gun within 1 second of reaching low ammo will increase its magazine size by 30% until the next reload.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[,],
    },
    100: {
        name:"Marked For Death",
        effect:"Mutations you ping are highlighted and your team deals 10% increased damage to highlighted enemies.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:["Mutation: Mutations are Special Ridden that are distinct from Common Ridden.",],
    },
    101: {
        name:"Knowledge is Power",
        effect:"+ 10% Weakspot Damage \n Allows players to see values for damage they deal and enemy health bars.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:["Weakspot: Most enmies have Weakspots that take extra damage when hit.",],
    },

    102: {
        name:"Tactical Vest",
        effect:"+ 30% Rifle Ammo Capacity \n + 10% Damage with Assault Rifles and LMGs",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },

    103: {
        name:"Experienced EMT",
        effect:"When you use a Medical Accessory, the target gains + 10% Maximum Health, Stamina and Stamina Regen until the end of the level.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },

    104: {
        name:"Weaponsmith",
        effect:"Allows the ability to unbolt attachments from weapons outside of Saferooms. Unbolting attachments costs 400 Copper.",
        team_effects:"Additional copies of Weaponsmith played reduce its cost by 100 copper.",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Tunnels of Terror",
        info:["Team Effect: This card applies to you and your teammates.",],
    },

    105: {
        name:"Over-Protective",
        effect:"When a teammate within 15 meters receives 5 or more damage, gain 20% increased Damage for 5 seconds.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Tunnels of Terror",
        info:[],
    },

    106: {
        name:"Experimental Stun Gun",
        effect:"Enhances Bash to stun nearby enemies. Refreshes after 10 seconds. \n Gadget Cost: 30 Sniper Ammo \n REPLACES: Quick Slot, FRAGILE",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Fragile: Effects removed after receiving damage."],
    },

    107: {
        name:"Crippling Frequency",
        effect:"Reduce incoming Damage by 1 for nearby teammates for 7 seconds. \n Gadget Cost: 30 SMG Ammo \n REPLACES: Offensive Slot",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.",],
    },

    108: {
        name:"Expired T5",
        effect:"Create a powerful blast that deals 20 Fire Damage to Weakspots. After the initial blast, continue to deal 1 damage per second for 7 seconds. \n Gadget Cost: 75 Rifle Ammo \n Replaces: Support Slot",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Weakspot: Most enmies have Weakspots that take extra damage when hit.",],
    },

    109: {
        name:"Sonic Disruptor",
        effect:"Emit a pulse that deals heavy Stumble damage to nearby enemies and has a chance to knock off armor. \n Gadget Cost: 75 SMG Ammo \n REPLACES: Offensive Slot",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Defense",
        expansion: "River of Blood",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Stumble: Stumble is a special damage type that builds up and interrupts enemies.",],
    },

    110: {
        name:"Hazmat Specialist",
        effect:"+ 35% Acid Resistance \n Your Bait Jars do direct damage to targets and can hit Weakspots.",
        team_effects:"Killing Mutations that are covered with Bait has a 75% chance to create another Bait Jar.",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "River of Blood",
        info:["Team Effect: This card applies to you and your teammates.","Weakspot: Most enmies have Weakspots that take extra damage when hit.","Mutation: Mutations are Special Ridden that are distinct from Common Ridden.",],
    },
    111: {
        name:"Wasteland Chef",
        effect:"Gain the ability to melee food items to create a Gourment Dinner or a Mediocre Meal. Using the Combat Knife increases your odds of a Gourmet Dinner.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Utility",
        expansion: "Standard",
        info:[],
    },
    112: {
        name:"Phosphorous Tipped",
        effect:"Continuous gunfire gives an escalating chance to set targets on fire.",
        team_effects:"",
        affinity: "Discipline",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    113: {
        name:"Vitamins",
        effect:"+25 Health",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    114: {
        name:"Hydration Pack",
        effect:"+35 Health \n -15% Ammo Capacity",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    115: {
        name:"Canned Goods",
        effect:"+45 Health \n -25% Stamina",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    116: {
        name:"Soften Up",
        effect:"Melee hits cause the target to deal 3% reduced damage, to a maximum of 15% reduced damage.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    117: {
        name:"Spiky Bits",
        effect:"+15 Melee Damage \n +20% Damage Resistance while using a Melee weapon \n -15% Ammo Capacity",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    118: {
        name:"Mean Drunk",
        effect:"+40% Melee Damage \n Your Melee Attacks cause cleave through enemies dealing damage in a large area.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    119: {
        name:"Durable",
        effect:"+15% Trauma Resistance \n +10 Health \n +20% Fire Resistance",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.", "Resistance: Reduces incoming damage (max: 90%).",],
    },
    120: {
        name:"Body Armor",
        effect:"+20% Trauma Resistance",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.", "Resistance: Reduces incoming damage (max: 90%).",],
    },
    121: {
        name:"Wooden Armor",
        effect:"30% Trauma Resistance \n -100% Fire Resistance",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Resistance: Reduces incoming damage (max: 90%).",],
    },
    122: {
        name:"Grenade Training",
        effect:"+25% Accessory Damage",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    123: {
        name:"Demoltioins Expert",
        effect:"+50% Accessory Damage \n -15% Ammo Capacity",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    124: {
        name:"Improvised Explosives",
        effect:"+75% Accessory Damage \n -25% Swap Speed",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    125: {
        name:"Confident Killer",
        effect:"When you or your team kills a Mutation, gain 1% damage (up to 15%) until the end of the level",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Mutation: Mutations are Special Ridden that are distinct from Common Ridden.",],
    },
    126: {
        name:"Heavy Hitter",
        effect:"Melee hits always Stumble Ridden the first time they are hit. This effect can only occur once per target.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Stumble: Stumble is a special damage type that builds up and interrupts enemies.",],
    },
    127: {
        name:"Ignore the Pain",
        effect:"+20% Melee Damage agains Mutations \n When you deal Melee damage to a Mutation heal 2 Health and 3 Stamina.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Mutation: Mutations are Special Ridden that are distinct from Common Ridden.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    128: {
        name:"Berserker",
        effect:"Each Melee kill grants 5% Melee Damage, 5% Melee Speed, and 5% Move Speed for 4 seconds.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    129: {
        name:"True Grit",
        effect:"When you take a single hit for 15 or more damage, recover 10 health over 5 seconds.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    130: {
        name:"Pyro",
        effect:"+100% Fire Damage. \nGain 3 Temporary Health for each kill with fire. \nYou can sense flammable objects nearby.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    131: {
        name:"Bomb Squad",
        effect:"1 Additional Frag Grenade spawns in each map.",
        team_effects:"+25% Team Explosive Damage \n+20% Team Explosive Resistance",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.","Resistance: Reduces incoming damage (max: 90%).",],
    },
    132: {
        name:"Scar Tissue",
        effect:"Take 1 less damage from all Ridden. \n +50% Acid Resistance",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    133: {
        name:"Battle Lust",
        effect:"Melee kills heal 1 Health and 0.125 Trauma.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    134: {
        name:"Line 'em Up",
        effect:"+10% Effective Bullet Range \n+15% Recoil Control \n+25% Bullet Penetration \n+25% Aim Speed",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    135: {
        name:"Face Your Fears",
        effect:"Heal 1 Temporary Health whenever you kill a Ridden within 2.5 meters",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    136: {
        name:"Well Fed",
        effect:"",
        team_effects:"+10 Team Health",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    137: {
        name:"Heavy Attack",
        effect:"Press [] with Melee weapons to perform a Heavy Attack. \n Heavy Attacks deal 100% increased damage and expend 50% more Stamina.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    138: {
        name:"Sunder",
        effect:"Melee hits cause the target to take 3% increased damage, to a maximum of 15% increased damage. \n Melee hits that destroy Armor have a chance to create usable Makeshift Armor.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    139: {
        name:"Overwatch",
        effect:"Kills from greater than 15 meters grant 5 Temporary Health to teammates within 15 meters of the target.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    140: {
        name:"Fresh Bandage",
        effect:"At the start of each level, recover 15 Trauma Damage, then recover any missing Health.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Saferoom: Effects that trigger in each Saferoom don't apply to transitioning to special levels, like Ridden Hives.",],
    },
    141: {
        name:"Defensive Maneuver",
        effect:"When you take a hit for 15 or more damage, gain 25% Damage Resistance for 3 seconds.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Resistance: Reduces incoming damage (max: 90%).",],
    },
    142: {
        name:"Two is One and One is None",
        effect:"You can equip a Primary weapon in your Secondary slot. \n -25% Swap Speed",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    143: {
        name:"Offensive Scavenger",
        effect:"Tou can sense nearby Offensive Accessories. \n More Offensive Accessories spawn.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Utility",
        expansion: "Standard",
        info:[],
    },
    144: {
        name:"Chemical Courage",
        effect:"Pain Meds you apply also grant +25% Damage for 60 seconds.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    145: {
        name:"Numb",
        effect:"Gain + 10% Damage Resistance while you have Temporary Health.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.","Resistance: Reduces incoming damage (max: 90%).",],
    },
    146: {
        name:"Broadside",
        effect:"Precision Kills have a 20% chance to cause Ridden to explode, dealing 15 damage to other Ridden within 4 meters.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Standard",
        info:["Precision Kill: Precision Kills trigger by getting a killing blow to a Weakspot.",],
    },
    147: {
        name:"Buckshot Bruiser",
        effect:"When using Shotguns, gain 0.25 Temporary Health for each pellet that hits.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    148: {
        name:"Second Chance",
        effect:"+1 Extra Life \n+15 Health \n+25% Bleed out Resistance",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Standard",
        info:["Extra Life: Each Extra Life increases the number of times you can be incapacitated without dying.",],
    },
    149: {
        name:"Power Strike",
        effect:"Every 3 seconds, gain +10 Bash Damage, stacking up to 10 times. All charges are consumed on use.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Tunnels of Terror",
        info:[],
    },
    150: {
        name:"Sadist",
        effect:"When a teammate within 15 meters receives 5 or more damage, gain 20% of the damage as Temporary Health. Can only trigger once per second.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:["Temporary Health: Temporary Health is Health that will steadily deplete, even when not taking damage.",],
    },
    151: {
        name:"Bodyguard",
        effect:"When a teammate within 5 meters is attacked, you instead receive 75% of that damage. Can trigger once every 5 seconds.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:[],
    },
    152: {
        name:"Bravado",
        effect:"When a teammate within 15 meters receives Trauma Damage, heal 15% of that amount as Trauma Health.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    153: {
        name:"Well Rested",
        effect:"",
        team_effects:"+ 20% Team Overheal \n+5% Team Healing Efficiency",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:["Team Effect: This card applies to you and your teammates.","Overheal: Overheal converts a portion of healing done beyond your maximum to Temporary Health.",],
    },
    154: {
        name:"Fit as a Fiddle",
        effect:"",
        team_effects:"+20% Team Bolstered Health \n+5 Team Health",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Tunnels of Terror",
        info:["Team Effect: This card applies to you and your teammates.","Bolstered Health: Bolstered Health is the amount beyond your normal maximum health that you can gain as Temporary Health, up to an additional 100%.",],
    },
    155: {
        name:"Ultrasonic Wound Therapy",
        effect:"Heal 6 Health over 7 seconds to nearby teammates. \nGadget Cost: 60 SMG AMMO \nREPLACES: Offensive Slot",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Defense",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Efficient Healing: The Healing from this card is affected by Healing efficiency Bonuses.",],
    },
    156: {
        name:"Out With a Bang",
        effect:"",
        team_effects:"When a teammate is incapacitated or dies, they drop an active Pipe Bomb.",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "Children of the Worm",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    157: {
        name:"Drone Spotter",
        effect:"Begin marking nearby Mutations every 7 seconds. Gain 20% chance to negate damage while active. \nGadget Cost: 20 SNIPER AMMO \nREPLACES: Quick Slot, FRAGILE",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Utility",
        expansion: "River of Blood",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Fragile: Effects removed after receiving damage.","Mutation: Mutations are Special Ridden that are distinct from Common Ridden.",],
    },
    158: {
        name:"Ether Bomb",
        effect:"Emit a gas that attracts Ridden to you for 7 seconds, but also slows your movement speed by 50%. \n Gadget Cost: 50 RIFLE AMMO \nREPLACES: Support Slot",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "River of Blood",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.",],
    },
    159: {
        name:"Empowered Assault",
        effect:"After you kill a Mutation, the next time you damage a Mutation is guaranteed to cause them to Stumble.",
        team_effects:"+5% Team Stumble Damage",
        affinity: "Brawn",
        card_type: "Offense",
        expansion: "River of Blood",
        info:["Team Effect: This card applies to you and your teammates.","Mutation: Mutations are Special Ridden that are distinct from Common Ridden.","Stumble: Stumble is a special damage type that builds up and interrupts enemies.",],
    },
    160: {
        name:"Cleansing Fire",
        effect:"Gain a stacking +5% Damage Resistance every second you're on fire, for a maximum 5 stacks lasting for 15 Seconds. \nFire Removes most negative status effects. \n+40% Fire Resistance.",
        team_effects:"",
        affinity: "Brawn",
        card_type: "Utility",
        expansion: "River of Blood",
        info:[],
    },
    161: {
        name:"Grenade Pouch",
        effect:"+1 Offensive Inventory \n+25% Swap Speed \n-5% Offensive Accessory Cost",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    162: {
        name:"Double Grenade Pouch",
        effect:"+2 Offensive Inventory",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    163: {
        name:"Surplus Pouches",
        effect:"-5% Health",
        team_effects:"+1 Team Offensive Inventory",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    164: {
        name:"Fanny Pack",
        effect:"+1 Support Inventory \n+15% Trauma Resistance",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Resistance: Reduces incoming damage (max: 90%).",],
    },
    165: {
        name:"Shoulder Bag",
        effect:"+2 Support Inventory",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Defense",
        expansion: "Standard",
        info:[],
    },
    166: {
        name:"Box o' Bags",
        effect:"-10% Health",
        team_effects:"+1 Team Support Inventory",
        affinity: "Fortune",
        card_type: "Defnse",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    167: {
        name:"Mugger",
        effect:"Kills with Melee weapons have a 5% chance to spawn ammo, Razor Wire or a Bear Trap.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:[],
    },
    168: {
        name:"Highwayman",
        effect:"Kills with Secondary guns have a 5% chance to spawn ammo, Molotov, or a Bait Jar.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:[],
    },
    169: {
        name:"Admin Reload",
        effect:"When you stow your weapon, it reloads.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    170: {
        name:"Bounty Hunter",
        effect:"When you or your team kills a Mutation, gain 10 Copper (up to 300 per level).",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Mutation: Mutations are Special Ridden that are distinct from Common Ridden.","Copper: Copper is a currency used to resupply and purchase items.",],
    },
    171: {
        name:"Ammo Stash",
        effect:"Your secondary weapons have unlimited ammo. \nYour secondary weapons reload 20% slower.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    172: {
        name:"Life Insurance",
        effect:"+2 Extra Life",
        team_effects:"+10% Reduced Incap Trauma",
        affinity: "Fortune",
        card_type: "Defense",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.","Extra Life: Each Extra Life increases the number of times you can be incapacitated without dying.","Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.",],
    },
    173: {
        name:"Wounded Animal",
        effect:"Kills while at Critical Health recover 1 Health.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "",
        expansion: "Standard",
        info:["Critical Health: Critical Health begins when a player is below 20% of their maximum Health.",],
    },
    174: {
        name:"Compound Interest",
        effect:"",
        team_effects:"Each Cleaner gains 5% of their total Copper in each Saferoom",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.","Copper: Copper is a currency used to resupply and purchase items.","Saferoom: Effects that trigger in each Saferoom don't apply to transitioning to special levels, like Ridden Hives.",],
    },
    175: {
        name:"Lucky Pennies",
        effect:"Whenever you or your team loots Copper, you have a 35% chance to find 100% additional Copper.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Copper: Copper is a currency used to resupply and purchase items.",],
    },
    176: {
        name:"Money Grubbers",
        effect:"Each time your team loots Copper, you gain 3 additional Copper, up to 25 times.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Copper: Copper is a currency used to resupply and purchase items.",],
    },
    177: {
        name:"Run and Gun",
        effect:"You can shoot while sprinting.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Mobility",
        expansion: "Standard",
        info:[],
    },
    178: {
        name:"Copper Scavenger",
        effect:"You can sense nearby Copper. \nMore Copper Piles spawn.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Copper: Copper is a currency used to resupply and purchase items.",],
    },
    179: {
        name:"Share the Wealth",
        effect:"",
        team_effects:"Each teammate gains 100 bonus Copper at the start of each level.",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.","Copper: Copper is a currency used to resupply and purchase items.","Saferoom: Effects that trigger in each Saferoom don't apply to transitioning to special levels, like Ridden Hives.",],
    },
    180: {
        name:"Shell Carrier",
        effect:"+30% Shotgun Ammo Capacity \n+10% Damage with Shotguns",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offense",
        expansion: "Standard",
        info:[],
    },
    181: {
        name:"Hazard Pay",
        effect:"Gain 250 bonus Copper athe start of each level.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Copper: Copper is a currency used to resupply and purchase items.","Saferoom: Effects that trigger in each Saferoom don't apply to transitioning to special levels, like Ridden Hives.",],
    },
    182: {
        name:"Saferoom Recovery",
        effect:"Your team recovers 15 Health, 7 Trauma Damage and refills 10% Ammo at the start of each level.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Defense",
        expansion: "Standard",
        info:["Trauma: Trauma is permanent damage that reduces your maximum health and is more difficult to restore.","Saferoom: Effects that trigger in each Saferoom don't apply to transitioning to special levels, like Ridden Hives.",],
    },
    183: {
        name:"Belt Clip",
        effect:"+1 Quick Slot Inventory \n +10% Use Speed",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Use Speed: Use Speed affects the time it takes to perform most actions with a progress bar.",],
    },
    184: {
        name:"Utility Belt",
        effect:"+2 Quick Slot Inventory",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:[],
    },
    185: {
        name:"Tool Belts",
        effect:"-10% Health",
        team_effects:"+1 Team Quick Slot Inventory",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
    186: {
        name:"Pinata",
        effect:"Killing Ridden with an Accessory has a 10% chance to drop an Accessory.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Tunnels of Terror",
        info:[],
    },
    187: {
        name:"Magician's Apprentice",
        effect:"You have an additional 10% chance to not consume Accessories when used.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Tunnels of Terror",
        info:[],
    },
    188: {
        name:"AI Assistant Module",
        effect:"5% Item Reuse chance that increases by 10% after every item used. Resets on Reuse. \nGadget Cost: 20 SNIPER AMMO \nREPLACES: Quick Slot, FRAGILE",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Children of the Worm",
        info:["Gadget: Replaces an accessory slot with an activatable ability that costs ammo to use. Cooldown, cost and effects stack for every Gadget occupying the same slot.","Fragile: Effects removed after receiving damage.",],
    },
    189: {
        name:"Belligerent",
        effect:"Gain a stacking 4% increase to Damage each time a Horde is called up to 6 stacks. (30 second cooldown between Hordes.) Stacks are reset when a Cleaner is incapped or killed.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Offnese",
        expansion: "Children of the Worm",
        info:[],
    },
    190: {
        name:"Food Scavenger",
        effect:"You can sesne nearby Food Items. \nAdds a moderate amount of Food Items to the world. \nFood Items restore an additional 3 Health.",
        team_effects:"",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Children of the Worm",
        info:[],
    },
    191: {
        name:"Ugly Chachkies",
        effect:"",
        team_effects:"Increases the number of Mementos in the world that can be collected for extra Supply Points. \nThis card does not spawn any Mementos in the Trial of the Worm.",
        affinity: "Fortune",
        card_type: "Utility",
        expansion: "Standard",
        info:["Team Effect: This card applies to you and your teammates.",],
    },
};

module.exports = card_data;